#spring:
#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    generate-unique-name: false

spring:
  datasource:
    username: bbung
    password: bbung1234!
    url: jdbc:mysql://localhost:3306/springboot