#spring:
#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    generate-unique-name: false

# postgresql
spring:
  datasource:
    username: bbung
    password: bbung1234!
    url: jdbc:postgresql://localhost:5432/springboot

# mysql
#spring:
#  datasource:
#    username: bbung
#    password: bbung1234!
#    url: jdbc:mysql://localhost:3306/springboot